Climeeting/climeet-fe

- src/axios.d.ts
- src/main.tsx
- src/pages/Home/HomePage.tsx
- src/pages/Home/Profile.tsx
- src/pages/Oauth/OauthPage.tsx
- src/pages/Oauth/hooks/api.ts
- src/pages/types/api.ts
- src/services/oauth.ts
- src/services/user.ts
- src/utils/api.ts
- src/utils/tanstack.ts
- vite.config.ts
#6 
- 로그인/로그아웃/유저정보 api 연결
- 비동기 상태인 유저 정보 tanstack query로 관리
- axios, tanstack query 기본 설정
> #6 로그인 / 유저 정보 관리

- package.json
- pnpm-lock.yaml
#24 
이전 PR에서 lock.yaml에서 충돌이 발생하여 다시 PR을 올렸습니다.
> #24 config: prettier 설치

- global.scss
- package.json
- pnpm-lock.yaml
- src/components/Chip.module.scss
- src/components/NavBar/BottomBar.module.scss
- src/components/Search.module.scss
- src/components/Select.module.scss
- src/components/ToggleButton.module.scss
- src/pages/Home/HomePage.module.scss
- src/pages/Home/HomePage.tsx
- src/pages/Home/Profile.tsx
- src/pages/Home/components/FilterBottomSheet.module.scss
- src/pages/Home/components/FilterBottomSheet.tsx
- src/pages/Home/components/FilterButton.module.scss
- src/pages/Home/components/FilterButton.tsx
- src/pages/Home/components/FilterList.tsx
- src/pages/Home/components/PartyCard.tsx
- src/pages/Home/components/Tabs.module.scss
- src/pages/Oauth/OauthPage.tsx
- tsconfig.json
- vite.config.ts
> #26 절대 경로 설정 & 컬러값 관리

- package.json
- pnpm-lock.yaml
- src/components/Slider.module.scss
- src/components/Slider.tsx
- src/pages/PartySurveyForm/components/PartyConditionForm.module.scss
- src/pages/PartySurveyForm/components/PartyConditionForm.tsx
1. 파티 조건 스텝 slider 구현
2. 상관없음 버튼 구현
> #41 파티 조건 스텝 slider 구현

- .eslintrc.cjs
> #43 eslint: react-refresh/only-export-components 에러 해결

- package.json
- pnpm-lock.yaml
- src/components/DatePicker.module.scss
- src/components/DatePicker.tsx
- src/main.tsx
- src/pages/Home/HomePage.tsx
- src/utils/dayjs.ts
#36 
- dayjs 설치하였습니다.
- DatePicker 컴포넌트를 생성했습니다.
> #36 DatePicker

- index.html
> #53 모바일 최적화

- global.scss
https://noonnu.cc/font_page/694
> #57 폰트 스타일 적용

- src/pages/PartySurveyForm/components/PartyIntroduceForm.module.scss
- src/pages/PartySurveyForm/components/PartyIntroduceForm.tsx
> #47 파티 소개 스텝 최소, 최대 글자 길이 체크하여 실시간 표시하는 기능 추가

- src/pages/PartySurveyForm/components/PartyIntroduceForm.tsx
파티 소개 스텝에서 글자 수를 최소, 최댓값을 만족하지 않을 경우 다음 스텝으로 이동할 수 없도록 기능을 추가하였습니다.
> #15 파티 소개 스텝 글자 수 유효성 검사 기능 추가

- package.json
- pnpm-lock.yaml
- src/components/ProgressBar.module.scss
- src/components/ProgressBar.tsx
- src/pages/PartySurveyForm/PartySurveyFormPage.tsx
- src/pages/PartySurveyForm/components/PartyPlaceForm.module.scss
- src/pages/PartySurveyForm/components/PartyPlaceForm.tsx
- src/pages/PartySurveyForm/components/PartyTypeForm.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
1. radix-ui의 progress 설치
2. ProgressBar 컴포넌트 생성
> #15 파티 생성 페이지 ProgressBar 추가

- src/pages/Home/components/PartyCard.tsx
- src/pages/PartyDetailPage/PartyDetailPage.tsx
- src/pages/PartyDetailPage/components/PartyDescription.module.scss
- src/pages/PartyDetailPage/components/PartyDescription.tsx
- src/pages/PartyDetailPage/components/PartyDetail.tsx
- src/pages/PartyDetailPage/components/PartyMainInfo.tsx
- src/pages/PartyDetailPage/components/PartyParticipants.module.scss
- src/pages/PartyDetailPage/components/PartyParticipants.tsx
- src/pages/PartySurveyForm/PartySurveyFormPage.tsx
- src/pages/types/api.ts
- src/services/party.ts
- src/services/user.ts
- 파티 디테일 페이지 api 연결
- tanstack query의 select를 사용하여 어뎁터 값 바로 추출하여 사용할 수 있도록 구현
- Suspense, ErrorBoundary 추가
> #65 파티 디테일 페이지

- src/components/NavBar/TopBar.tsx
- src/pages/PartySurveyForm/PartySurveyFormPage.tsx
- src/pages/PartySurveyForm/components/PartyTypeForm.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
1. 파티 생성 뒤로가기 구현
2. TopBar 컴포넌트 props 추가
> #80 파티 생성 뒤로가기 구현

- src/components/NavBar/TopBar.tsx
- src/pages/PartySurveyForm/PartySurveyFormPage.tsx
- src/pages/PartySurveyForm/components/PartyPlaceForm.module.scss
- src/pages/PartySurveyForm/components/PartyPlaceForm.tsx
- src/pages/PartySurveyForm/components/PartyTypeForm.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
1. 검색 리스트 스크롤 추가
2. 검색 디바운스 추가
> #79 파티 생성의 암장 검색 추가 기능 개발

- src/components/BottomSheet.module.scss
- src/components/ScrollPicker.module.scss
- src/components/ScrollPicker.tsx
- src/pages/Home/components/FilterBottomSheet.tsx
- src/pages/Home/components/FilterList.tsx
- src/pages/PartySurveyForm/components/PartyConditionForm.module.scss
- src/pages/PartySurveyForm/components/PartyConditionForm.tsx
- src/pages/PartySurveyForm/components/PartyIntroduceForm.tsx
- src/pages/PartySurveyForm/components/PartyPlaceForm.module.scss
- src/pages/PartySurveyForm/components/PartyScheduleForm.module.scss
- src/pages/PartySurveyForm/components/PartyScheduleForm.tsx
- src/pages/PartySurveyForm/components/PartyTypeForm.tsx
- src/pages/PartySurveyForm/hooks/useTimePicker.ts
scroll-snap-type이 아닌 방식으로 구현을 먼저 하였습니다. 추후 변경할 생각입니다.
> #77 Scroll Picker 생성 및 적용

- src/components/NavBar/TopBar.module.scss
- src/components/NavBar/TopBar.tsx
- src/pages/Login/LoginPage.tsx
- src/pages/MyUpdatePage/MyUpdatePage.tsx
- src/pages/PartyDetailPage/PartyDetailPage.tsx
- src/pages/PartySurveyForm/components/PartyTypeForm.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
- src/pages/UserPage/UserPage.tsx
- src/pages/UserPage/components/Profile.tsx
- src/reset.css
- src/services/user.ts
TopBar 를 헤드리스 패턴으로 리팩토링하여
재사용에 용의하도록 수정하였습니다.
> #90 TopBar headless UI

- src/pages/Home/HomePage.tsx
- src/pages/Home/components/GymSearch.module.scss
- src/pages/Home/components/GymSearch.tsx
- src/pages/PartySurveyForm/components/PartyPlaceForm.tsx
- src/services/gymSearch.ts
- src/utils/useClimbingGymSearch.tsx
1. 암장 검색 로직 커스텀 훅으로 분리
2. 홈페이지 암장 검색 모달 구현
3. 암장 검색 모달의 최근 검색어 표시 기능 구현
1. 검색된 암장 정보를 api 요청에 추가하는 작업 필요
> #88 홈페이지 암장 검색 기능 구현

- src/pages/PartySurveyForm/components/PartyPreview.module.scss
- src/pages/PartySurveyForm/components/PartyPreview.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
1. 파티 생성 전 미리보기 구현 (실내, 실외 모두)
2. 파티 생성 컴포넌트의 useStepFlow 제거
> #92 파티 생성 미리보기 구현

- src/pages/Home/HomePage.module.scss
- src/pages/Home/HomePage.tsx
- src/pages/Home/components/GymSearch.tsx
- src/pages/Home/components/PartyList.tsx
- src/pages/Home/hooks/useSearchContext.tsx
> #98 홈화면 파티 리스트 api 에 locationId 전달하여 필터링

- src/pages/Home/components/PartyCard.tsx
- src/pages/types/api.ts
> #106 홈화면 암장 이름 노출

- package.json
- pnpm-lock.yaml
- src/pages/MyNewPage/MyNewPage.tsx
- src/pages/MyUpdatePage/MyUpdatePage.tsx
- src/pages/MyUpdatePage/components/MyUpdateForm.tsx
- src/pages/MyUpdatePage/components/PreviewImage.tsx
- src/pages/MyUpdatePage/components/SaveButton.tsx
- src/pages/MyUpdatePage/hooks/useFileContext.tsx
- src/pages/MyUpdatePage/hooks/useMyInfoForm.tsx
- src/pages/PartyDetailPage/components/PartyParticipants.tsx
- src/pages/types/api.ts
- src/services/party.ts
- src/services/user.ts
- src/utils/s3.ts
- vite.config.ts
#103 
- skill => skillLevel로 변수명 수정 (skill, skillLevel로 변수명이 혼용되고 있어 하나로 통일)
- aws-sdk를 사용해서 S3에 이미지 업로드
- 이미지 파일 컨텍스트 api를 사용해 사용자 입력 파일을 S3에 업로드
> #103 S3에 이미지 업로드

- src/pages/MyUpdatePage/components/SaveButton.tsx
- src/services/user.ts
fix: 유저 정보 업데이트시 변경된 내용만 api 요청에 담아서 보냄
> #117 fix: 유저 정보 업데이트시 변경된 내용만 api 요청에 담아서 보냄

- src/pages/PartyEditFormPage/PartyEditFormPage.tsx
- src/pages/PartySurveyForm/PartySurveyFormPage.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
- src/services/party.ts
> #125 파티 생성 미완성 작업 완료

- src/pages/Home/HomePage.module.scss
- src/pages/Home/HomePage.tsx
- src/pages/Home/components/PartyCard.module.scss
- src/pages/Home/components/PartyCard.tsx
- src/pages/Home/hooks/useDateContext.tsx
- src/pages/Home/hooks/useFilterContext.tsx
- src/pages/Home/hooks/useFilterParams.tsx
- src/pages/types/api.ts
- src/utils/s3.ts
#124
- position: sticky 를 활용하여 스크롤시 필터영역 상단에 고정
https://www.figma.com/design/RWgmHPPUSKKC75CmtbuInf/%ED%81%B4%EB%9D%BC%EC%9D%B4%EB%B0%8B?node-id=2272-2600&t=GPIvR7efha3vOM8Y-0
- feat: 홈화면 필터 값들 로컬 스토리지에 저장
- feat: 파티 카드에 썸네일 추가
- [feat: s3 경로 매개변수로 확장](https://github.com/Climeeting/climeet-fe/pull/133/commits/510c9cec9023746166277673453a3f092f4f51c1)
> #124 홈화면 작업

- src/pages/PartyDetailPage/components/PartyMainInfo.module.scss
- src/pages/PartyDetailPage/components/PartyMainInfo.tsx
- src/pages/UserPage/UserPage.module.scss
- src/pages/UserPage/UserPage.tsx
- src/pages/UserPage/components/Profile.tsx
- src/pages/routes.tsx
- src/pages/types/api.ts
- src/services/user.ts
> #127 유저페이지 관련 작업

- src/pages/PartyDetailPage/components/PartyMainInfo.tsx
- src/pages/UserPage/RedirectUserPage.tsx
- src/pages/UserPage/UserPage.tsx
- src/pages/UserPage/hook/useIsMine.ts
- src/pages/routes.tsx
- src/pages/types/api.ts
> #127 my page

- src/components/Icon/svgs/close.svg
- src/pages/UserPage/UserPage.tsx
- src/pages/UserPage/components/PartyCardList.tsx
- src/pages/UserPage/components/PartyFilter.module.scss
- src/pages/UserPage/components/PartyFilter.tsx
- src/pages/UserPage/hook/useDateRangeContext.tsx
- src/services/user.ts
> #142 user page filter

- package.json
- pnpm-lock.yaml
- src/components/Toast.module.scss
- src/components/Toast.tsx
- src/pages/PartyDetailPage/components/PartyBottomButton.tsx
- src/services/party.ts
#145
https://github.com/user-attachments/assets/512b0f68-b549-434b-aa4f-fbd3f01e3a65
리팩토링 필요..
> #145 파티 참여시 예외처리 (토스트 사용)

- src/pages/PartyDetailPage/components/MoreMenu.tsx
- 파티 상세 페이지에서 파티 수정으로 이동하는 로직을 추가하였습니다,
> #151 파티 수정 이동 로직 추가

- src/pages/DeleteAccountPage/DeleteAccountPage.module.scss
- src/pages/DeleteAccountPage/DeleteAccountPage.tsx
- src/pages/DeleteAccountPage/SelectWithdrawReason.module.scss
- src/pages/DeleteAccountPage/SelectWithdrawReason.tsx
> #137 회원 탈퇴 UI 변경

- src/pages/MyUpdatePage/components/SaveButton.tsx
- src/pages/PartySurveyForm/components/PartyPreview.module.scss
- src/pages/PartySurveyForm/components/PartyPreview.tsx
- src/pages/PartySurveyForm/components/Steps.tsx
> #175 handle async

- src/services/party.ts
- src/services/user.ts
> #177 서버 에러 응답이 없는 경우엔 기본 메시지 노출하도록 개선
